-- MySQL Script generated by MySQL Workbench
-- Tue May 26 14:43:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema withTrip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema withTrip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `withTrip` DEFAULT CHARACTER SET utf8 ;
USE `withTrip` ;

-- -----------------------------------------------------
-- Table `withTrip`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`member` (
  `id` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `age` INT NOT NULL,
  `gender` VARCHAR(5) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `date` DATETIME NOT NULL,
  `point` INT NOT NULL,
  `type` VARCHAR(400) NOT NULL,
  `cp_3` INT NOT NULL DEFAULT 0,
  `cp_5` INT NOT NULL DEFAULT 0,
  `cp_10` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `member_phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`region` (
  `region_code` INT NOT NULL,
  `region_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`place` (
  `pl_num` INT NOT NULL,
  `region_code` INT NOT NULL,
  `pl_name` VARCHAR(200) NOT NULL,
  `pl_content` VARCHAR(6000) NOT NULL,
  `pl_address` VARCHAR(1000) NOT NULL,
  `pl_image` VARCHAR(400) NOT NULL,
  `pl_readcount` INT NOT NULL,
  `pl_likecount` INT NOT NULL,
  `pl_date` DATETIME NOT NULL,
  `pl_theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pl_num`, `region_code`),
  INDEX `fk_board_region1_idx` (`region_code` ASC),
  CONSTRAINT `fk_board_region1`
    FOREIGN KEY (`region_code`)
    REFERENCES `withTrip`.`region` (`region_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`place_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`place_comment` (
  `pc_num` INT NOT NULL,
  `pc_content` VARCHAR(45) NOT NULL,
  `pc_date` DATETIME NOT NULL,
  `member_member_id` VARCHAR(45) NOT NULL,
  `pct_rank` INT NOT NULL,
  `place_place_num` INT NOT NULL,
  PRIMARY KEY (`pc_num`),
  INDEX `fk_place_comment_member1_idx` (`member_member_id` ASC),
  INDEX `fk_place_comment_place1_idx` (`place_place_num` ASC),
  CONSTRAINT `fk_place_comment_member1`
    FOREIGN KEY (`member_member_id`)
    REFERENCES `withTrip`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_place_comment_place1`
    FOREIGN KEY (`place_place_num`)
    REFERENCES `withTrip`.`place` (`pl_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`product` (
  `p_num` INT NOT NULL,
  `p_name` VARCHAR(200) NOT NULL,
  `p_content` VARCHAR(1000) NOT NULL,
  `p_image` VARCHAR(500) NOT NULL,
  `p_price` VARCHAR(45) NOT NULL,
  `p_amount` INT NOT NULL,
  `p_category` VARCHAR(300) NULL,
  `region_region_code` INT NOT NULL,
  PRIMARY KEY (`p_num`),
  INDEX `fk_product_region1_idx` (`region_region_code` ASC),
  CONSTRAINT `fk_product_region1`
    FOREIGN KEY (`region_region_code`)
    REFERENCES `withTrip`.`region` (`region_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`event_box`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`event_box` (
  `eb_num` INT NOT NULL AUTO_INCREMENT,
  `eb_rank` INT NOT NULL DEFAULT 0,
  `eb_pull` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`eb_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`event` (
  `e_round` INT NOT NULL AUTO_INCREMENT,
  `e_sdate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `e_edate` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`e_round`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`event_win`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`event_win` (
  `ew_num` INT NOT NULL AUTO_INCREMENT,
  `member_id` VARCHAR(45) NOT NULL,
  `event_round` INT NOT NULL,
  `ew_date` DATETIME NOT NULL,
  PRIMARY KEY (`ew_num`),
  INDEX `fk_event_list_member1_idx` (`member_id` ASC),
  INDEX `fk_event_win_list_event1_idx` (`event_round` ASC),
  CONSTRAINT `fk_event_list_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `withTrip`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_win_list_event1`
    FOREIGN KEY (`event_round`)
    REFERENCES `withTrip`.`event` (`e_round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`review` (
  `r_num` INT NOT NULL,
  `member_member_id` VARCHAR(20) NOT NULL,
  `r_subject` VARCHAR(200) NOT NULL,
  `r_content` VARCHAR(2000) NOT NULL,
  `r_readcount` INT NOT NULL,
  `r_likecount` INT NOT NULL,
  `r_date` DATETIME NOT NULL,
  `r_image` VARCHAR(500) NOT NULL,
  `region_region_code` INT NOT NULL,
  PRIMARY KEY (`r_num`, `member_member_id`),
  INDEX `fk_review_member1_idx` (`member_member_id` ASC),
  INDEX `fk_review_region1_idx` (`region_region_code` ASC),
  CONSTRAINT `fk_review_member1`
    FOREIGN KEY (`member_member_id`)
    REFERENCES `withTrip`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_region1`
    FOREIGN KEY (`region_region_code`)
    REFERENCES `withTrip`.`region` (`region_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`suggestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`suggestion` (
  `sg_num` INT NOT NULL,
  `member_member_id` VARCHAR(45) NOT NULL,
  `sg_content` VARCHAR(2000) NOT NULL,
  `sg_email` VARCHAR(45) NOT NULL,
  `sg_date` DATETIME NOT NULL,
  `sg_check` VARCHAR(45) NOT NULL,
  `sg_subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sg_num`),
  INDEX `fk_suggestion_member1_idx` (`member_member_id` ASC),
  CONSTRAINT `fk_suggestion_member1`
    FOREIGN KEY (`member_member_id`)
    REFERENCES `withTrip`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`survey` (
  `s_num` INT NOT NULL,
  `s_question` VARCHAR(300) NOT NULL,
  `s_sdate` DATETIME NOT NULL,
  `s_edate` DATETIME NOT NULL,
  `s_wdate` DATETIME NOT NULL,
  PRIMARY KEY (`s_num`),
  UNIQUE INDEX `servey_title_UNIQUE` (`s_question` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`surveyResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`surveyResult` (
  `sr_listnum` INT NOT NULL,
  `sr_itemnum` VARCHAR(45) NULL,
  `sr_item` VARCHAR(45) NULL,
  `sr_count` INT NULL,
  `survey_s_num` INT NOT NULL,
  PRIMARY KEY (`sr_listnum`),
  INDEX `fk_survey_result_survey1_idx` (`survey_s_num` ASC),
  CONSTRAINT `fk_survey_result_survey1`
    FOREIGN KEY (`survey_s_num`)
    REFERENCES `withTrip`.`survey` (`s_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`review_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`review_comment` (
  `rc_num` INT NOT NULL,
  `review_review_num` INT NOT NULL,
  `review_member_member_id` VARCHAR(20) NOT NULL,
  `rc_content` VARCHAR(2000) NOT NULL,
  `rc_date` DATE NOT NULL,
  `rc_ref` INT NOT NULL,
  `rc_seq` INT NOT NULL,
  `rct_lev` INT NOT NULL,
  PRIMARY KEY (`rc_num`),
  INDEX `fk_review_comment_review1_idx` (`review_review_num` ASC, `review_member_member_id` ASC),
  CONSTRAINT `fk_review_comment_review1`
    FOREIGN KEY (`review_review_num` , `review_member_member_id`)
    REFERENCES `withTrip`.`review` (`r_num` , `member_member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`cart` (
  `c_num` INT NOT NULL,
  `c_p_num` INT NOT NULL,
  `c_member_id` VARCHAR(45) NULL,
  `c_p_amount` INT NULL,
  PRIMARY KEY (`c_num`),
  INDEX `fk_basket_product1_idx` (`p_num` ASC),
  CONSTRAINT `fk_basket_product1`
    FOREIGN KEY (`p_num`)
    REFERENCES `withTrip`.`product` (`p_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`order` (
  `order_num` INT NOT NULL,
  `order_name` VARCHAR(45) NOT NULL,
  `order_phone` VARCHAR(45) NOT NULL,
  `order_type` VARCHAR(45) NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  `order_date` VARCHAR(45) NOT NULL,
  `member_member_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_num`),
  INDEX `fk_order_member1_idx` (`member_member_id` ASC),
  CONSTRAINT `fk_order_member1`
    FOREIGN KEY (`member_member_id`)
    REFERENCES `withTrip`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `withTrip`.`orderDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `withTrip`.`orderDetail` (
  `od_num` INT NOT NULL,
  `od_goods_name` VARCHAR(45) NOT NULL,
  `od_content` VARCHAR(45) NOT NULL,
  `od_price` VARCHAR(45) NOT NULL,
  `od_amount` VARCHAR(45) NOT NULL,
  `order_order_num` INT NOT NULL,
  `product_product_num` INT NOT NULL,
  PRIMARY KEY (`od_num`),
  INDEX `fk_orderdetail_order1_idx` (`order_order_num` ASC),
  INDEX `fk_orderdetail_product1_idx` (`product_product_num` ASC),
  CONSTRAINT `fk_orderdetail_order1`
    FOREIGN KEY (`order_order_num`)
    REFERENCES `withTrip`.`order` (`order_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetail_product1`
    FOREIGN KEY (`product_product_num`)
    REFERENCES `withTrip`.`product` (`p_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
